public enum State {
    IDLE,
    WAITING_FOR_NAME,
    WAITING_FOR_GUESS,
    WAITING_FOR_QUESTION,
    WAITING_FOR_WEATHER_CITY,
    WAITING_FOR_HUMAN_CHOICE,
    WAITING_FOR_REVERSE,
    WAITING_FOR_CONFIRM,

}

